<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <RootNamespace>ModbusExt.ProfileEditor</RootNamespace>
    <AssemblyName>ModbusExt.ProfileEditor</AssemblyName>
  </PropertyGroup>
</Project>